services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ads_user
      POSTGRES_PASSWORD: ads_password
      POSTGRES_DB: ads_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: